### ISSUE TITLE
get integration tests passing

### ISSUE THREAD

**Issue by displague** [packet-labs/google-anthos#125]
Integrations are currently failing with:
```

module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec): Trying to connect to ESX Host . . .
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec): Connected to ESX Host !
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec): Successfully created vSwitch  vSwitch1
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec): Successfully created PortGroup  Management
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec): Traceback (most recent call last):
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec):   File "/root/bootstrap/esx_host_networking.py", line 353, in <module>
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec):     main()
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec):   File "/root/bootstrap/esx_host_networking.py", line 211, in main
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec):     create_port_group(host_network_system, "Management", vswitch_name, subnet['vlan'])
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec):   File "/root/bootstrap/esx_host_networking.py", line 76, in create_port_group
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec):     host_network_system.AddPortGroup(portgrp=port_group_spec)
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec):   File "/usr/local/lib/python3.6/dist-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec):     self.f(*(self.args + (obj,) + args), **kwargs)
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec):   File "/usr/local/lib/python3.6/dist-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec):     return self._stub.InvokeMethod(self, info, args)
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec):   File "/usr/local/lib/python3.6/dist-packages/pyVmomi/SoapAdapter.py", line 1397, in InvokeMethod
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec):     raise obj # pylint: disable-msg=E0702
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec): pyVmomi.VmomiSupport.AlreadyExists: (vim.fault.AlreadyExists) ***
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec):    dynamicType = <unset>,
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec):    dynamicProperty = (vmodl.DynamicProperty) [],
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec):    msg = "The specified key, name, or identifier 'pgName' already exists.",
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec):    faultCause = <unset>,
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec):    faultMessage = (vmodl.LocalizableMessage) [],
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec):    name = 'pgName'
module.vsphere.null_resource.apply_esx_network_config[0] (remote-exec): ***

module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec): Trying to connect to ESX Host . . .
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec): There was a connection Error to host: 147.75.70.58. Sleeping 10 seconds and trying again.
module.vsphere.null_resource.apply_esx_network_config[1]: Still creating... [2m50s elapsed]
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec): Trying to connect to ESX Host . . .
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec): Connected to ESX Host !
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec): Successfully created vSwitch  vSwitch1
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec): Successfully created PortGroup  Management
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec): Traceback (most recent call last):
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec):   File "/root/bootstrap/esx_host_networking.py", line 353, in <module>
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec):     main()
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec):   File "/root/bootstrap/esx_host_networking.py", line 211, in main
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec):     create_port_group(host_network_system, "Management", vswitch_name, subnet['vlan'])
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec):   File "/root/bootstrap/esx_host_networking.py", line 76, in create_port_group
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec):     host_network_system.AddPortGroup(portgrp=port_group_spec)
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec):   File "/usr/local/lib/python3.6/dist-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec):     self.f(*(self.args + (obj,) + args), **kwargs)
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec):   File "/usr/local/lib/python3.6/dist-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec):     return self._stub.InvokeMethod(self, info, args)
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec):   File "/usr/local/lib/python3.6/dist-packages/pyVmomi/SoapAdapter.py", line 1397, in InvokeMethod
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec):     raise obj # pylint: disable-msg=E0702
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec): pyVmomi.VmomiSupport.AlreadyExists: (vim.fault.AlreadyExists) ***
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec):    dynamicType = <unset>,
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec):    dynamicProperty = (vmodl.DynamicProperty) [],
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec):    msg = "The specified key, name, or identifier 'pgName' already exists.",
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec):    faultCause = <unset>,
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec):    faultMessage = (vmodl.LocalizableMessage) [],
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec):    name = 'pgName'
module.vsphere.null_resource.apply_esx_network_config[1] (remote-exec): ***
```

**Comment by displague** [comment]
Once complete, we may wish to create a new issue for performing Anthos specific testing (per #91).
